GAT: true
GCN: false
GIN: false
add_mlp: true
aggregation_fn: sum
batch_norm: false
batch_size: 32
benchmark_idx: true
clique_persistence: true
dataset: ENZYMES
deepset: true
deepset_type: shallow
depth: 4
dim0_out_dim: 16
dim1: true
dim1_out_dim: 8
dist_dim1: true
dist_dimh: true
dropout_edges_p: 0
dropout_input_p: 0
dropout_p: 0.1
fake: false
filtration_hidden: 24
fold: 0
full_deepset_highdims: true
hidden_dim: 256
higher_dims:
- 2
higher_dims_out_dim:
- 8
legacy: true
lift_to_simplex: true
lr: 0.0001
lr_patience: 15
max_epochs: 1000
max_simplex_dim: 2
merged: false
min_lr: 0.0001
mlp_combine_dims_clique_persistence: false
model: TopoGNN
num_coord_funs: 4
num_filtrations: 2
num_heads_gnn: 3
paired: false
print_stats: false
relu_filtrations: false
residual: true
residual_and_bn: false
save_filtration: false
seed: 42
separate_filtration_functions: true
share_filtration_parameters: false
strong_reg_check: false
swap_bn_order: true
tanh_filtrations: false
togl_position: 1
train_eps: false
training_seed: 42
use_node_attributes: false
weight_decay: 0.1
