GAT: true
GCN: false
GIN: false
add_mlp: false
aggregation_fn: mean
batch_norm: false
batch_size: 128
benchmark_idx: true
clique_persistence: true
dataset: MNIST
deepset: true
deepset_type: linear
depth: 3
dim0_out_dim: 32
dim1: true
dim1_out_dim: 32
dist_dim1: true
dist_dimh: true
dropout_edges_p: 0
dropout_input_p: 0
dropout_p: 0.2
fake: false
filtration_hidden: 24
fold: 0
full_deepset_highdims: false
hidden_dim: 256
higher_dims:
- 2
higher_dims_out_dim:
- 16
legacy: true
lift_to_simplex: true
lr: 0.0005
lr_patience: 15
max_epochs: 1000
max_simplex_dim: 2
merged: false
min_lr: 1.0e-06
mlp_combine_dims_clique_persistence: true
model: TopoGNN
num_coord_funs: 3
num_filtrations: 2
num_heads_gnn: 2
paired: false
print_stats: false
relu_filtrations: false
residual: false
residual_and_bn: true
save_filtration: false
seed: 42
separate_filtration_functions: false
share_filtration_parameters: false
strong_reg_check: false
swap_bn_order: true
tanh_filtrations: true
togl_position: 0
train_eps: true
training_seed: 42
use_node_attributes: true
weight_decay: 0
