GAT: false
GCN: false
GIN: true
GatedGCN: false
add_mlp: false
aggregation_fn: mean
batch_norm: true
batch_size: 32
benchmark_idx: true
clique_persistence: true
dataset: DD
deepset: true
deepset_type: shallow
depth: 4
dim0_out_dim: 64
dim1: true
dim1_out_dim: 16
dist_dim1: true
dist_dimh: true
dropout_edges_p: 0.2
dropout_input_p: 0.2
dropout_p: 0.2
fake: false
filtration_hidden: 32
fold: 0
full_deepset_highdims: true
hidden_dim: 128
higher_dims:
- 2
higher_dims_out_dim:
- 64
legacy: true
lift_to_simplex: true
lr: 0.001
lr_patience: 5
max_epochs: 1000
max_simplex_dim: 2
merged: false
min_lr: 0.0001
mlp_combine_dims_clique_persistence: false
model: TopoGNN
num_coord_funs: 2
num_filtrations: 4
num_heads_gnn: 3
paired: false
print_stats: false
relu_filtrations: false
residual: false
residual_and_bn: true
save_filtration: false
seed: 42
separate_filtration_functions: false
share_filtration_parameters: true
strong_reg_check: false
swap_bn_order: false
tanh_filtrations: false
togl_position: 1
train_eps: false
training_seed: 42
use_node_attributes: true
weight_decay: 0.1

